from __future__ import annotations


def build_pdf_prompt() -> str:
    return (
        "PDF behavior:\n"
        "- If, and only if, the user explicitly asks to \"create\", \"generate\", "
        "\"export\", \"save\" or \"download\" a PDF (in any language), you MUST in addition "
        "to the normal assistant answer emit a structured JSON specification for the PDF document.\n"
        "- After finishing the human-readable answer, append a line starting with the exact marker: "
        "PDF_DOC_JSON:\n"
        "- Immediately after that marker, output ONLY a valid JSON object (no markdown, no prose) "
        "describing the PDF, using this schema:\n"
        "  {\n"
        "    \"title\": string,                // short document title\n"
        "    \"subtitle\": string | null,      // optional subtitle or context\n"
        "    \"author\": string | null,        // optional author/owner name\n"
        "    \"sections\": [                   // ordered content blocks\n"
        "      {\n"
        "        \"title\": string,           // section heading\n"
        "        \"body\": string             // plain text body; use line breaks for lists, no markdown\n"
        "      },\n"
        "      ...\n"
        "    ],\n"
        "    \"tables\": [                    // optional tabular data blocks\n"
        "      {\n"
        "        \"title\": string | null,   // optional table caption\n"
        "        \"headers\": [string, ...], // column headers\n"
        "        \"rows\": [                 // table rows, all as strings\n"
        "          [string, ...],\n"
        "          ...\n"
        "        ]\n"
        "      },\n"
        "      ...\n"
        "    ],\n"
        "    \"footer\": string | null        // optional short footer (e.g. legal note or summary)\n"
        "  }\n"
        "- Keep text inside the JSON plain (no markdown, no HTML, no emojis).\n"
        "- Use clear, professional wording. Prefer short paragraphs (1-3 sentences each).\n"
        "- For lists, use line breaks with numbered items like \"1) ...\", \"2) ...\".\n"
        "- Use title case for section titles and keep them concise.\n"
        "- For tables, every row must have the same number of columns as headers.\n"
        "- If a value is unknown, use \"Not specified\" rather than inventing details.\n"
        "- Do NOT mention the word \"PDF\" inside the JSON fields themselves; it is implied by the context.\n"
        "- If the user did not ask for a PDF, do not add the PDF_DOC_JSON marker at all.\n"
    )
